version: '3.1'
services:
  java:
    restart: always
    image: javaImage
    environment:
      - JAVA_OPTS=-server -Xms512m -Xmx512m -Xmn512m -XX:MaxMetaspaceSize=512m  -Dspring.profiles.active=test
    volumes:
    ports:
      - 8080:8080
