version: '3.1'
services:
   sentinel:
      image: hb0730/alibaba-sentinel
      restart: always
      container_name: sentinel
      volumes:
        - ./logs:/root/logs
        - ./config:/home/sentinel/config
      ports:
        - '8080:8080'
        - '8719:8719'