version: '3.1'
services:
   ui:
      image:  ui
      restart: always
      container_name: ui
      networks:
        - docker-net
      environment:
        TZ: 'Asia/Shanghai'
networks:
   docker-net:
     external: true
